spring:
  datasource:
    url: jdbc:mysql://mysql-server:3306/security?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
    username: ubuntu
    password: 12345@ABcd


  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:7000/eureka
    register-with-eureka: true
    fetch-registry: true